env:
  GITHUB_REPO: "lcarneirofreitas/buildkite-test"
  DEV_ACCOUNT: "1234567890"
  PROD_ACCOUNT: "0987654321"

steps:

  # Step 1: Verifica a Label no PR
  - label: "Verificando Label no PR"
    key: check-label
    command: |
      echo "Verificando labels do PR #${BUILDKITE_PULL_REQUEST}..."
      LABELS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                   "https://api.github.com/repos/$GITHUB_REPO/issues/${BUILDKITE_PULL_REQUEST}/labels" | jq -r '.[].name')

      echo "Labels encontradas: $LABELS"

      if echo "$LABELS" | grep -q "dev"; then
        echo "Iniciando deploy para DEV..."
        echo "BUILDKITE_TRIGGER_ENV=dev" >> "$BUILDKITE_ENV_FILE"
      elif echo "$LABELS" | grep -q "production"; then
        echo "Iniciando deploy para PRODUÇÃO..."
        echo "BUILDKITE_TRIGGER_ENV=production" >> "$BUILDKITE_ENV_FILE"
      else
        echo "Nenhuma label válida encontrada. Cancelando build."
        buildkite-agent annotate "Pipeline cancelado: Nenhuma label válida encontrada." --style "error"
        exit 1
      fi
    agents:
      queue: "default"

  - wait

  # Step 2: Build e Testes (Somente se a Label foi identificada)
  - label: "Build & Test"
    key: build-test
    command: |
      echo "Rodando build..."
      echo "Executando testes..."
      sleep 5
      echo "Build e testes finalizados com sucesso!"
    agents:
      queue: "default"

  - wait

# Step 3: Deploy em Dev
- label: "Deploy em Dev"
  key: deploy-dev
  command: |
    if [[ "$BUILDKITE_TRIGGER_ENV" == "dev" ]]; then
      echo "Iniciando deploy em Dev..."
      sleep 5
      echo "Deploy em Dev finalizado!"
    else
      echo "Skipping deploy para Dev"
      exit 0
    fi
  agents:
    queue: "default"

# Step 4: Aprovação para Deploy em Produção
- input: "Aprovar Deploy em Produção?"
  key: approve-prod
  depends_on:
    - build-test
  prompt: "Deseja implantar a versão em Produção?"
  command: |
    if [[ "$BUILDKITE_TRIGGER_ENV" != "production" ]]; then
      echo "Skipping approval step for production"
      exit 0
    fi

# Step 5: Deploy em Produção
- label: "Deploy em Produção"
  key: deploy-prod
  depends_on:
    - approve-prod
  command: |
    if [[ "$BUILDKITE_TRIGGER_ENV" == "production" ]]; then
      echo "Iniciando deploy em Produção..."
      sleep 5
      echo "Deploy em Produção finalizado!"
    else
      echo "Skipping deploy para Produção"
      exit 0
    fi
  agents:
    queue: "default"
